remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
exclude: ['*.Rmd']
plugins:
  - jekyll-spaceship
  - jekyll-toc
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
