---
title: "CCBB"
output: 
  # html_document:
  md_document:
date: "2023-12-27"
---


<a href="index.html" class="home-button">Home</a>


# Table of Contents {.tabset}

## Pages

- [About](subpages/about.html)
- [Services](subpages/services.html)
- [Sequencing](subpages/sequencing.html)
- [Publications](subpages/publications.html)
- [Submit Request](subpages/submit_request.html)
- [Research](subpages/research.html)
- [Team](subpages/team.html)
- [Resources](subpages/resources.html)
- [Contact](subpages/contact.html)

## Tutorials

- [CCBB Guidelines](tutorials/CCBB_guidelines.html)
- [CCBB Project Guidelines](tutorials/CCBB_project_guidelines.html)
- [CCBB Publications](tutorials/CCBB_publications.html)
- [CCBB Services Epigenomics](tutorials/CCBB_services_epigenomics.html)
- [CCBB Services Genomics](tutorials/CCBB_services_genomics.html)
- [CCBB Services Metagenomics](tutorials/CCBB_services_metagenomics.html)
- [CCBB Services Transcriptomics](tutorials/CCBB_services_transcriptomics.html)
- [FileZilla Instructions CCBB](tutorials/FileZilla_Instructions_CCBB.html)
- [RNAseq Pipeline Tutorial](tutorials/rnaseqpipeline.html)