---
title: "CCBB Services Epigenomics"
output: 
  html_document:
    css: "../style.css"
date: "2023-12-27"
---

# Center for Computational Biology and Bioinformatics (CCBB)

# 2022 - CCBB Services: Epigenomics


**ChIP-Seq/eCLIP-Seq/CUT&RUN/RIP-Seq, ATAC-Seq**


ChIP-Seq/eCLIP-Seq/CUT&RUN/RIP-Seq (standard Level 1 services: ~3 to 5 business days)




**Requirements:**
<ol>
* Read targets reached (e.g. ~ 10 million reads per sample; human genome) for each of your samples in the study

* Number of samples submitted are less than 10

* Sample metadata (description of ChIP and INPUT samples) shared with CCBB prior to sequencing

* Biological replicates, if any, for your ChIP samples

* Reference genomes considered as standard: human, mouse, rat

</ol>




**Level 1 services:** CCBB effort level - 2 hours


**Standard analysis:** Alignment to reference genome using BWA, peak calling (using protocol specific peak callers), BigWig files, HOMER to annotate peaks relative to gene features along with QC plots/tables.




**Level 2 services:** CCBB effort level - 5 hours

* Level 1 services + Motif discovery

* Help with visualization







**Level 3 services:** Consult CCBB first! CCBB effort level no more than 8 hours short term collaboration less than one month

* Large datasets with more than 20 samples

* Multiple sets of standard analysis

* Integration analysis (e.g. ChIP-Seq and RNA-Seq)

* Contribution to writing a scientific paper including Methods section







**ATAC-Seq (standard level 1 service: ~3 to 5 business days)**




**Level 1 services:** CCBB effort level - 2 hours


**Standard analysis:** Alignment to reference genome using BWA, MACS2 for peak-calling, bed and BigWig files, HOMER to annotate peaks relative to gene features.




**Level 2 services:** CCBB effort level - 5 hours

* Motif searching

* ATAC_ChIP and RNA-Seq

* TF Footprinting

* DE analysis







**Email to <a href="mailto:ccbb.at.scripps.edu">ccbb.at.scripps.edu</a> to set up a consultation meeting for additional service(s).**




**Additional services:** Consult CCBB to get a quote/estimation of effort in hours. CCBB service hourly charges apply.

* Software development, custom pipeline implementation

* Re-analysis of older datasets

* Analysis for public datasets

* Specific figures/tables for publications; writing methods section or contribution for scientific papers/grant proposals

* Functional Analysis using Advaita/GSEA/SetRank

* Letter of Support for grants

* GEO/SRA submissions


